name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Code auschecken
      uses: actions/checkout@v4

    - name: Python installieren
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Abhängigkeiten installieren
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Projekt bauen
      run: |
        python -m build

    - name: Paket testen
      run: |
        pip install .
        pi-cipher encrypt "Test"
